version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
      args:
        - SERVER_NAME=localhost
        - WEBAPP_PORT=8000
    image: castlemilk/demo1-proxy:v1
    ports:
      - 80:80
    networks:
      - frontend
  webapp:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    entrypoint: /django-entrypoint.sh
    image: castlemilk/demo1-webapp:v1
    volumes:
      - .:/django
    expose:
      - 8000
    networks:
      - frontend
      - backend
  postgres:
    restart: always
    image: postgres:10
    expose:
      - 5432
    volumes:
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres/data:/var/lib/postgresql
    networks:
      - backend

networks:
  frontend:
  backend: